import localFont from "next/font/local";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";

import { ThemeProvider } from "@/components/custom/theme-provider";

import { cn } from "@/lib/utils";
import { ModeToggle } from "@/components/custom/ToggleBtn";
import Sidebar from "@/components/custom/sidebar";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="p-3">
            <ModeToggle />
          </div>

        <div className="flex flex-wrap gap-5">
          
        <div className="w-2/12 md:3/12">
            <Sidebar />
          </div>  

          <div className="w-9/12 md:w-8/12">
            {children}
          </div>
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
